use "term.sig";
use "term.sml";
open term;

use "form.sig";
use "form.sml";
open form;

use "logic.sig";
use "logic.sml";
open logic;

use "pp.sig";
use "pp.sml";
open pp;

use "token.sig";
use "token.sml";
open token;

use "pterm_dtype.sml";
open pterm_dtype;

use "pterm.sig";
use "pterm.sml";
open pterm;

use "drule.sig";
use "drule.sml";
open drule;

use "infixes.sml";
use "abbrev.sig";
use "abbrev.sml";
open abbrev;


use "conv.sig"; 
use "conv.sml";
open conv;

use "tactic.sig";
use "tactic.sml";
open tactic;


use "goalstack.sig";
use "goalstack.sml";
open goalstack;



(*
use "form.sig";
use "form.sml";
use "logic.sig";
use "logic.sml";

open term form logic;

use "pp.sig";
use "pp.sml";

open pp;

use "token.sig";
use "token.sml";
use "pterm_dtype.sml";
use "pterm.sig";
use "pterm.sml";

open token pterm_dtype pterm;

use "drule.sig";
use "drule.sml";
open drule;

use "infixes.sml";
use "abbrev.sig";
use "abbrev.sml";

open abbrev;

use "conv.sig"; 
use "conv.sml";
use "tactic.sig";
use "tactic.sml";

open conv tactic;

use "goalstack.sig";
use "goalstack.sml";

open goalstack;

*)
